apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: subtensor-mainnet-lite  # This selector matches the pods labeled with 'app: subtensor-mainnet-lite'.
  type: LoadBalancer
  ports:
    - name: rpc-port
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p-port
      protocol: TCP
      port: 30333
      targetPort: 30333
    - name: ws-port
      protocol: TCP
      port: 9933
      targetPort: 9933
